import { describe, expect, it } from "vitest";
import { openApiDocument } from "../../src/config/swagger";

const criticalOperations = [
  ["/health", "get"],
  ["/api", "get"],
  ["/api/media/audio/{storageKey}", "get"],
  ["/api/auth/signup", "post"],
  ["/api/auth/login", "post"],
  ["/api/auth/refresh", "post"],
  ["/api/auth/logout", "post"],
  ["/api/auth/me", "get"],
  ["/api/auth/me", "patch"],
  ["/api/auth/me", "delete"],
  ["/api/auth/me/password", "patch"],
  ["/api/auth/me/notifications", "put"],
  ["/api/auth/google", "post"],
  ["/api/projects", "get"],
  ["/api/projects", "post"],
  ["/api/projects/{projectId}", "get"],
  ["/api/projects/{projectId}", "patch"],
  ["/api/projects/{projectId}", "delete"],
  ["/api/projects/{projectId}/members", "get"],
  ["/api/projects/{projectId}/members/invite", "post"],
  ["/api/projects/{projectId}/members/{userId}", "patch"],
  ["/api/projects/{projectId}/members/{userId}", "delete"],
  ["/api/projects/{projectId}/transfer-ownership", "post"],
  ["/api/projects/{projectId}/kanban/columns", "get"],
  ["/api/projects/{projectId}/kanban/columns", "post"],
  ["/api/projects/{projectId}/kanban/columns/order", "put"],
  ["/api/projects/{projectId}/kanban/columns/{columnId}", "patch"],
  ["/api/projects/{projectId}/kanban/columns/{columnId}", "delete"],
  ["/api/projects/{projectId}/tasks", "get"],
  ["/api/projects/{projectId}/tasks", "post"],
  ["/api/projects/{projectId}/tasks/{taskId}", "get"],
  ["/api/projects/{projectId}/tasks/{taskId}", "patch"],
  ["/api/projects/{projectId}/tasks/{taskId}", "delete"],
  ["/api/projects/{projectId}/tasks/{taskId}/activity", "get"],
  ["/api/projects/{projectId}/tasks/{taskId}/comments", "get"],
  ["/api/projects/{projectId}/tasks/{taskId}/comments", "post"],
  ["/api/projects/{projectId}/overview", "get"],
  ["/api/projects/{projectId}/meetings", "get"],
  ["/api/projects/{projectId}/meetings", "post"],
  ["/api/projects/{projectId}/meetings/transcript", "post"],
  ["/api/projects/{projectId}/meetings/audio", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}", "get"],
  ["/api/projects/{projectId}/meetings/{meetingId}/audio", "get"],
  ["/api/projects/{projectId}/meetings/{meetingId}/transcript", "get"],
  ["/api/projects/{projectId}/meetings/{meetingId}/tasks", "get"],
  ["/api/projects/{projectId}/meetings/{meetingId}/status", "patch"],
  ["/api/projects/{projectId}/meetings/{meetingId}/reprocess", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates", "get"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/{candidateId}", "patch"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/{candidateId}", "delete"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/{candidateId}/approve", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/{candidateId}/reject", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/{candidateId}/restore", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/bulk-approve", "post"],
  ["/api/projects/{projectId}/meetings/{meetingId}/candidates/bulk-reject", "post"],
  ["/api/projects/{projectId}/duplicates/{duplicateId}/resolve", "post"],
  ["/api/notifications", "get"],
  ["/api/notifications/{notificationId}/read", "patch"],
  ["/api/notifications/read-all", "post"],
  ["/api/projects/{projectId}/commands", "post"],
  ["/api/projects/{projectId}/commands/{commandId}", "get"],
  ["/api/projects/{projectId}/commands/{commandId}/confirm", "post"],
  ["/api/projects/{projectId}/commands/{commandId}/cancel", "post"],
] as const;

describe("OpenAPI coverage", () => {
  it.each(criticalOperations)("documents %s %s", (path, method) => {
    expect(openApiDocument.paths[path]?.[method]).toBeDefined();
  });
});
